package ccompiler.lexer;

public enum LexerTokenType {
    INTEGER,
    LEFT_PARANTHESIS, RIGHT_PARANTHESIS, COLON, SEMI_COLON, LEFT_SQUARE_BRACKET, RIGHT_SQUARE_BRACKET,
    LEFT_CURLY_BRACKET, RIGHT_CURLY_BRACKET, COMMA, UNKNOWN, STRING, KEYWORD, TYPE, ID, ASSIGNMENT, TILDE, DOT, AT, PLUS, MINUS, MULTIPLY, DIVIDE, SMALLER, SMALLER_EQUALS, EQUALS, RIGHT_ARROW
}
